Canteen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ddu_canteen.urls')),
    
    

]
"""path('register/registration_done', user_views.registration_done, name = 'registration_done')"""

ddu_canteen/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='homepage'),
    path('login/', views.login, name='login'),
    path('cart/', views.cart, name='cart'),
    path('register/', views.register, name = 'register'),
    path('update_item/', views.updateItem, name = 'update_item'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ddu_canteen/models.py
from django.conf import settings
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User

CATEGORY_CHOICES = (
    ('SN', 'snacks'),
    ('BR', 'breakfast'),
    ('LU', 'lunch'),
    ('BE', 'beverages')
)

LABEL_CHOICES = (
    ('S', 'students-choice'),
    ('N', 'new')
)

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    college_id = models.CharField(max_length= 10)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    name = models.CharField(max_length = 20)
    price = models.FloatField()
    photo = models.ImageField(upload_to='images/')
    category = models.CharField(choices = CATEGORY_CHOICES, max_length = 2, default= 'LU')
    label = models.CharField(choices = LABEL_CHOICES, max_length = 1, default= 'N')

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.photo.url
        except:
            url = ''
        return url


class Order(models.Model):
    student = models.ForeignKey(Student , on_delete=models.SET_NULL, blank=True, null=True)
    # """items = models.ManyToManyField(OrderItem)"""
    complete = models.BooleanField(default=False, null=True, blank=False)
    date_ordered = models.DateTimeField(auto_now_add=True, blank=True)
    transaction_id = models.CharField(max_length=16, null = True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([ item.get_total for item in orderitems])
        return total
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([ item.quantity for item in orderitems])
        return total
# """class Banners(models.Model):
#     image = models.ImageField(upload_to = 'banners')"""

class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True, blank=True)
    quantity = models.IntegerField(default=1)

    @property
    def get_total(self):
        total = self.item.price * self.quantity
        return total

ddu_canteen/views.py
from typing import ItemsView
from django.shortcuts import render, redirect
from .models import *
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.db.models import F
from django.http import JsonResponse
import json
import requests
import random

def home(request):
    order, created = Order.objects.get_or_create(complete=False)
    items = order.orderitem_set.all()
    cartItems = order.get_cart_items
    content = {
        'items': Item.objects.all(),
        'item':items, 'order':order,
        'cartItems':cartItems
    }
    return render(request, 'ddu_canteen/home.html' , content)

def register(request):
    if request.method == "POST":
        print("Registered")
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        id = request.POST['college_id']
        p1 = request.POST['pass']
        p2 = request.POST['re-pass']
        email = request.POST['email']
        phone = request.POST['phone']
        p = str(phone)
        fn = str(firstname)

        # user = User(username = username, first_name=firstname, last_name=lastname, email = email, password = p1)
        # user.save()
        # student = Student(user = user, college_id=id)
        # student.save()

        url = "https://www.fast2sms.com/dev/bulk"
        # querystring = {"authorization":"","sender_id":"TXTIND","message":"Welcome","route":"dlt","numbers":p}

        # headers = {
        #     'cache-control': "no-cache"
        # }

        # response = requests.request("GET", url, headers=headers, params=querystring)
        otp = random.randint(1000,9999)
        o = str(otp)
        # print(response.text) 
        my_data = { 
            # Your default Sender ID 
            'sender_id': 'TXTIND',  
            
            # Put your message here! 
            'message': 'Welcome to bunkORNER, '+fn+ ' Your OTP is '+ o,  
            
            'language': 'english', 
            'route': 'p', 
            
            # You can send sms to multiple numbers 
            # separated by comma. 
            'numbers': p    
        }
        headers = { 
            'authorization': 'auth_keys', 
            'Content-Type': "application/x-www-form-urlencoded", 
            'Cache-Control': "no-cache"
        }
        response = requests.request("POST", 
                            url, 
                            data = my_data, 
                            headers = headers)
        print(response)
        return redirect('/')
    else:
        return render(request, 'ddu_canteen/register.html')


def login(request):
    return render(request, 'ddu_canteen/login.html')

def cart(request):
    # if request.user.is_authenticated:
    #     user = request.user
    #     student = Student.objects.get(user=F('user'))
    #     print(student)
    #     order, created = Order.objects.get_or_create(student=student, complete=False)
    #     items = order.orderitem_set.all()
    # else:
    #     items = []
    user = request.user
    order, created = Order.objects.get_or_create(complete=False)
    items = order.orderitem_set.all()
    cartItems = order.get_cart_items
    context = {'items':items, 'order':order, 'cartItems':cartItems}
    return render(request, 'ddu_canteen/cart.html', context)

def updateItem(request):
    data = json.loads(request.body)
    itemId = data['itemId']
    action = data['action']
    print('Action:', action)
    print('ItemId:', itemId)

    user = request.user
    item = Item.objects.get(id=itemId)
    # student = Student.objects.get(user=user)
    order, created = Order.objects.get_or_create(complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, item = item)
    if(action == 'add'):
        orderItem.quantity = (orderItem.quantity + 1)
    elif(action == 'remove'):
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()
    if orderItem.quantity < 0:
        orderItem.delete()
    return JsonResponse('Item was Added', safe=False)






        # email_subject = 'Activate your Account'
        # email_body =  'Click on the link to activate your bunkORNER account'
        # email = EmailMessage(
        #     email_subject,
        #     email_body,
        #     'noreply@tehhet.com',
        #     [email],
            
        # )
        # send_mail(
        #     email_subject,
        #     email_body,
        #     'tyewatson0@gmail.com',
        #     ['gautamrizwani@gmail.com', email],
        #     fail_silently=False
        # )
        # mail = EmailMessage(
        #     email_subject,
        #     email_body,
        #     'tyewatson0@gmail.com',
        #     ['gautamrizwant@gmail.com', email]
        # )
        # mail.send(fail_silently=False)

    """def registration_done(request):
    if request.method == "POST":
        print("Registered")
        name = request.POST['name']
        id = request.POST['college_id']
        p1 = request.POST['pass']
        p2 = request.POST['re-pass']
        email = request.POST['email']

        info = Student(name=name, college_id=id, password=p1, email=email)
        info.save()
        return redirect("ddu_canteen/home.html")
    else:
        print("No request")"""

ddu_canteen/templates/ddu_canteen/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DDU's Canteen</title>
    <link rel="stylesheet" href="{% static 'ddu_canteen/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'ddu_canteen/css/bootstrap.min.css' %}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'ddu_canteen/images/favicon.png' %}" >
    <link rel="apple-touch-icon" href="{% static 'ddu_canteen/images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'ddu_canteen/css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'ddu_canteen/css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'ddu_canteen/css/custom.css' %}">

    <script type="text/javascript">
        var user = '{{request.user}}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>
</head>
<body>
    <header class="main-header">
        <!-- Start Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-default bootsnav">
            <div class="container">
                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand" href="index.html"><img src="{% static 'ddu_canteen/images/logo.png' %}" class="logo" alt=""></a>
                </div>
                <!-- End Header Navigation -->

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="nav navbar-nav ml-auto" data-in="fadeInDown" data-out="fadeOutUp">
                        <li class="nav-item active"><a class="nav-link" href="homepage">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="about.html">About Us</a></li>
                        
                        <li class="nav-item"><a class="nav-link" href="gallery.html">Gallery</a></li>
                        <li class="nav-item"><a class="nav-link" href="register">Register</a></li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->

                <!-- Start Atribute Navigation -->
                <div class="attr-nav">
                    <ul>
                        {% comment %} <li class="search"><a href="#"><i class="fa fa-search"></i></a></li> {% endcomment %}
                        <li class="side-menu">
							<a href="cart">
								<i class="fa fa-shopping-bag"></i>
								<span class="badge">3</span>
								<p>My Plate</p>
                                <p class ="badge">{{cartItems}}</p>
							</a>
						</li>
                    </ul>
                </div>
                <!-- End Atribute Navigation -->
            </div>
            <!-- Start Side Menu -->
            <div class="side">
                <a href="#" class="close-side"><i class="fa fa-times"></i></a>
                <li class="cart-box">
                    <ul class="cart-list">
                        {%for i in item%}
                            <li>
                                <a href="#" class="photo"><img src="{{i.item.imageURL}}" class="cart-thumb" alt="" /></a>
                                <h6><a href="#">{{i.item.name}}</a></h6>
                                <p>{{i.quantity}}x - <span class="price">₹{{i.get_total}}</span></p>
                            </li>
                        {%endfor%} 
                        
                        <li class="total">
                            <a href="cart" class="btn btn-default hvr-hover btn-cart">VIEW PLATTER</a>
                            <span class="float-right"><strong>Total</strong>: ₹{{ order.get_cart_total }}</span>
                        </li>
                    </ul>
                </li>
            </div>
            <!-- End Side Menu -->
        </nav>
        <!-- End Navigation -->
    </header>
    <!-- End Main Top -->

    {% block content %}{% endblock %}

    <!-- Start Footer  -->
    <footer>
        <div class="footer-main">
            <div class="container">
				<div class="row">
					<div class="col-lg-4 col-md-12 col-sm-12">
						<div class="footer-top-box">
							<h3>Canteen Time</h3>
							<ul class="list-time">
								<li>Monday - Friday: 08.00am to 05.00pm</li> <li>Saturday: 10.00am to 08.00pm</li> <li>Sunday: <span>Closed</span></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-4 col-md-12 col-sm-12">
						<div class="footer-top-box">
							<h3>Social Media</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
							<ul>
                                <li><a href="#"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-google-plus" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-rss" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-pinterest-p" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-whatsapp" aria-hidden="true"></i></a></li>
                            </ul>
						</div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <div class="footer-link-contact">
                            <h3>Contact Us</h3>
                            <ul>
                                <li>
                                    <p><i class="fas fa-map-marker-alt"></i>Address:Ddit College Canteen,<br> Ddu University, Sh 61,<br>Nadiad - 387001 </p>
                                </li>
                                <li>
                                    <p><i class="fas fa-phone-square"></i>Phone: <a href="tel:+9102682520502">+9102682520502</a></p>
                                </li>
                                <li>
                                    <p><i class="fas fa-envelope"></i>Email: <a href="mailto:canteen@ddu.ac.in">canteen@ddu.ac.in</a></p>
                                </li>
                            </ul>
                        </div>
                    </div>
				</div>
            </div>
        </div>
    </footer>
    <!-- End Footer  -->

    <!-- Start copyright  -->
    <div class="footer-copyright">
        <p class="footer-company">bunkORNER &copy; 2021 <a href="https://www.instagram.com/_het.shah_/">Het Shah</a> & <a href="https://www.instagram.com/gautam_rizwani/">Gautam Rizwani</a></p>
    </div>
    <!-- End copyright  -->

    <a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>
    
    <!-- ALL JS FILES -->
    <script src="{% static 'ddu_canteen/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/popper.min.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/bootstrap.min.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'ddu_canteen/js/jquery.superslides.min.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/bootstrap-select.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/inewsticker.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/bootsnav.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/images-loded.min.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/isotope.min.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/baguetteBox.min.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/form-validator.min.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/contact-form-script.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/custom.js' %}"></script>
    <script src="{% static 'ddu_canteen/js/cart.js' %}"></script>
    

</body>

</html>

ddu_canteen/templates/ddu_canteen/home.html
{% extends "ddu_canteen/base.html" %}
{% load static %}
{% block content %}
    <!-- Start Top Search -->
    <div class="top-search">
        <div class="container">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                <input type="text" class="form-control" placeholder="Search">
                <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
            </div>
        </div>
    </div>
    <!-- End Top Search -->
    <!-- Start Slider -->
    <div id="slides-shop" class="cover-slides">
        <ul class="slides-container">
            <li class="text-center">
                <img src="{% static 'ddu_canteen/images/ban1.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> bunkORNER</strong></h1>
                            <p class="m-b-40">Bunk Your CLASSES<br> Not Your HUNGER</p>
                            <p><a class="btn hvr-hover" href="#menu">Order Now</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'ddu_canteen/images/ban2.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> bunkORNER</strong></h1>
                            <p class="m-b-40">Bunk Your CLASSES<br> Not Your HUNGER</p>                            <p><a class="btn hvr-hover" href="#">Order Now</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'ddu_canteen/images/ban3.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> bunkORNER</strong></h1>
                            <p class="m-b-40">Bunk Your CLASSES<br> Not Your HUNGER</p>                            <p><a class="btn hvr-hover" href="#">Order Now</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'ddu_canteen/images/ban4.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> bunkORNER</strong></h1>
                            <p class="m-b-40">Bunk Your CLASSES<br> Not Your HUNGER</p>                            <p><a class="btn hvr-hover" href="#">Order Now</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'ddu_canteen/images/ban5.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> bunkORNER</strong></h1>
                            <p class="m-b-40">Bunk Your CLASSES<br> Not Your HUNGER</p>                            <p><a class="btn hvr-hover" href="#">Order Now</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'ddu_canteen/images/ban6.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> bunkORNER</strong></h1>
                            <p class="m-b-40">Bunk Your CLASSES<br> Not Your HUNGER</p>                            <p><a class="btn hvr-hover" href="#">Order Now</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'ddu_canteen/images/ban7.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> bunkORNER</strong></h1>
                            <p class="m-b-40">Bunk Your CLASSES<br> Not Your HUNGER</p>                            <p><a class="btn hvr-hover" href="#">Order Now</a></p>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <div class="slides-navigation">
            <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
        </div>
    </div>
    <!-- End Slider -->
	
	

    <!-- Start Products  -->
    <div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1 id="menu">Menu</h1>
                        <p>Satisfy Your Snack Attack</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="special-menu text-center">
                        <div class="button-group filter-button-group">
                            <button class="active" data-filter="*">All</button>
                            <button data-filter=".breakfast">Breakfast</button>
                            <button data-filter=".lunch">Lunch</button>
                            <button data-filter=".snacks">Snacks</button>
                            <button data-filter=".beverages">Beverages</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row special-list">
            {% for item in items %}
                
                <div data-items="{{item.name}}" data-action="add" class="update-cart col-lg-3 col-md-6 special-grid {{ item.get_category_display }}">
                    <div class="products-single fix">
                        <div class="box-img-hover">
                            <div class="type-lb">
                                <p class="{{ item.get_label_display }}" >{{ item.get_label_display }}</p>
                            </div>
                            <img src="{{item.imageURL}}" class="img-fluid" alt="Image">
                            <div class="mask-icon">
                                <ul>    
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Favorites"><i class="far fa-heart"></i></a></li>
                                </ul>
                                {% comment %} <a data-item="{{item.price}}" data-action="add" class="cart">Add to Platter</a> {% endcomment %}
                                <button class="cart btn" onclick="update_item('{{item.id}}', 'add')">Add to Platter</button>
                                {% comment %} <button class="cart btn" onclick="add_to_cart({{item.id}}, '{{item.name}}', {{item.price}})">Add to Platter</button> {% endcomment %}
                            </div>
                        </div>
                        
                        <div class="why-text">
                            <h4>{{item.name}}</h4>
                            <h5>₹{{item.price}}</h5>
                        </div>
                    </div>
                </div>

            {%endfor%}
            </div>    
    
            </div>
        </div>
    </div>
    <!-- End Products  -->

    <div class="box-add-products">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12">
					<div class="offer-box-products">
						<img class="img-fluid" src="images/add-img-01.jpg" alt="" />
					</div>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12">
					<div class="offer-box-products">
						<img class="img-fluid" src="images/add-img-02.jpg" alt="" />
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

ddu_canteen/templates/ddu_canteen/otp.html
{% extends 'ddu_canteen/base.html' %}
{% block content %}
    <!-- Start Register  -->
    <div class="contact-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-sm-12">
                    <div class="contact-form-right">
                        <form action ="{% url 'otp' %}" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="otp" placeholder="OTP" autocomplete="off" required data-error="Enter Valid OTP">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                
                                <div class="col-md-12">
                                    <div class="submit-button text-center">
                                        <button class="btn hvr-hover" type="submit" value="submit">Enter Otp</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
				<div class="col-lg-4 col-sm-12">
                    <div class="contact-info-left">
                        <h2>CONTACT INFO</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent urna diam, maximus ut ullamcorper quis, placerat id eros. Duis semper justo sed condimentum rutrum. Nunc tristique purus turpis. Maecenas vulputate. </p>
                        <ul>
                            <li>
                                <p><i class="fas fa-map-marker-alt"></i>Address:Ddit College Canteen,<br> Ddu University, Sh 61,<br>Nadiad - 387001 </p>
                            </li>
                            <li>
                                <p><i class="fas fa-phone-square"></i>Phone: <a href="tel:+9102682520502">+9102682520502</a></p>
                            </li>
                            <li>
                                <p><i class="fas fa-envelope"></i>Email: <a href="mailto:canteen@ddu.ac.in">canteen@ddu.ac.in</a></p>
                            </li>
                        </ul>    
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}